# Licensing of the files that cannot carry an SPDX header themselves.
# Source files state their own license in their header (see LICENSE and LICENSE-MIT).
version = 1

[[annotations]]
path = ["README.md", "CONTRIBUTING.md", "CITATION.cff", "pyproject.toml", ".gitignore", ".github/**", "REUSE.toml", "examples/until_1990/.gitignore", "examples/until_1990/.dvcignore", "examples/until_1990/.dvc/**"]
SPDX-FileCopyrightText = "2026 Alfredo Hernández Inostroza and the Scientographer contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
